services:

  app:

    image: myapp:latest  # Replace with your app image

    build: .

    ports:

      - "8080:8080"

    environment:

      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb

      SPRING_DATASOURCE_USERNAME: postgres

      SPRING_DATASOURCE_PASSWORD: example

    depends_on:

      - db



  db:

    image: postgres:15

    restart: always

    environment:

      POSTGRES_DB: mydb

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: example

    ports:

      - "5432:5432"

    volumes:

      - db_data:/var/lib/PostgreSQL/data



volumes:

  db_data: